language: python
compiler: gcc
dist: xenial

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: "3.8-dev"

  allow_failures:
    - python: "3.8-dev"

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - binutils
      - graphviz
      - python-pip

# command to install dependencies
install:
    - export FC=/usr/bin/gfortran
    - pip install -r requirements.travis.txt
    - pip install https://github.com/modflowpy/flopy/zipball/develop
    - pip install nose-timer
    - pip install coveralls

# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - nosetests -v --with-id --with-timer -w ./autotest --with-coverage --cover-package=pymake
after_success:
    - coveralls
